---
# tasks file for common
# - name: Print all available facts
#   ansible.builtin.debug:
#     var: ansible_facts
- name: install epel
  yum: name=epel-release state=installed
  when:
      - ansible_facts['os_family'] is defined and  ansible_facts['os_family'] == "RedHat"

- name: disable selinux
  ansible.posix.selinux:
    state: disabled

- name: set timezone
  command: timedatectl set-timezone {{ timezone }}

- name: make serverspec node directory
  local_action: file path={{ serverspec_base_dir }}/spec/{{ inventory_hostname }} state=directory mode=0755 owner={{ serverspec_exec_user_name }} group={{ serverspec_exec_user_group }}
  tags:
    - serverspec

- name: put spec file of serverspec
  local_action: template src=common_spec.rb.j2 dest={{ serverspec_base_dir }}/spec/{{ inventory_hostname }}/common_spec.rb
  tags:
    - serverspec
